"""initial schema from ERD

Revision ID: e8313ed1427e
Revises: 
Create Date: 2026-09-25 13:33:28.593277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8313ed1427e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id_user'), 'user', ['id_user'], unique=False)
    op.create_table('goal',
    sa.Column('id_goal', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('judul_goal', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_goal')
    )
    op.create_index(op.f('ix_goal_id_goal'), 'goal', ['id_goal'], unique=False)
    op.create_index(op.f('ix_goal_id_user'), 'goal', ['id_user'], unique=False)
    op.create_table('mood_questionnaire',
    sa.Column('id_questionnaire', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('hasil_akhir', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_questionnaire')
    )
    op.create_index(op.f('ix_mood_questionnaire_id_questionnaire'), 'mood_questionnaire', ['id_questionnaire'], unique=False)
    op.create_index(op.f('ix_mood_questionnaire_id_user'), 'mood_questionnaire', ['id_user'], unique=False)
    op.create_table('time_constraint',
    sa.Column('id_constraint', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('hari_dalam_minggu', sa.Integer(), nullable=False),
    sa.Column('waktu_mulai', sa.Time(), nullable=False),
    sa.Column('waktu_selesai', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_constraint')
    )
    op.create_index(op.f('ix_time_constraint_id_constraint'), 'time_constraint', ['id_constraint'], unique=False)
    op.create_index(op.f('ix_time_constraint_id_user'), 'time_constraint', ['id_user'], unique=False)
    op.create_table('milestone',
    sa.Column('id_milestone', sa.Integer(), nullable=False),
    sa.Column('id_goal', sa.Integer(), nullable=False),
    sa.Column('judul_milestone', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_goal'], ['goal.id_goal'], ),
    sa.PrimaryKeyConstraint('id_milestone')
    )
    op.create_index(op.f('ix_milestone_id_goal'), 'milestone', ['id_goal'], unique=False)
    op.create_index(op.f('ix_milestone_id_milestone'), 'milestone', ['id_milestone'], unique=False)
    op.create_table('questionnaire_answer',
    sa.Column('id_answer', sa.Integer(), nullable=False),
    sa.Column('id_questionnaire', sa.Integer(), nullable=False),
    sa.Column('nomor_questionnaire', sa.Integer(), nullable=False),
    sa.Column('nilai_jawaban', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_questionnaire'], ['mood_questionnaire.id_questionnaire'], ),
    sa.PrimaryKeyConstraint('id_answer')
    )
    op.create_index(op.f('ix_questionnaire_answer_id_answer'), 'questionnaire_answer', ['id_answer'], unique=False)
    op.create_index(op.f('ix_questionnaire_answer_id_questionnaire'), 'questionnaire_answer', ['id_questionnaire'], unique=False)
    op.create_table('task',
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('id_milestone', sa.Integer(), nullable=False),
    sa.Column('id_parent_task', sa.Integer(), nullable=True),
    sa.Column('nama_task', sa.String(length=255), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('durasi_estimasi', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_milestone'], ['milestone.id_milestone'], ),
    sa.ForeignKeyConstraint(['id_parent_task'], ['task.id_task'], ),
    sa.PrimaryKeyConstraint('id_task')
    )
    op.create_index(op.f('ix_task_id_milestone'), 'task', ['id_milestone'], unique=False)
    op.create_index(op.f('ix_task_id_parent_task'), 'task', ['id_parent_task'], unique=False)
    op.create_index(op.f('ix_task_id_task'), 'task', ['id_task'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_id_task'), table_name='task')
    op.drop_index(op.f('ix_task_id_parent_task'), table_name='task')
    op.drop_index(op.f('ix_task_id_milestone'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_questionnaire_answer_id_questionnaire'), table_name='questionnaire_answer')
    op.drop_index(op.f('ix_questionnaire_answer_id_answer'), table_name='questionnaire_answer')
    op.drop_table('questionnaire_answer')
    op.drop_index(op.f('ix_milestone_id_milestone'), table_name='milestone')
    op.drop_index(op.f('ix_milestone_id_goal'), table_name='milestone')
    op.drop_table('milestone')
    op.drop_index(op.f('ix_time_constraint_id_user'), table_name='time_constraint')
    op.drop_index(op.f('ix_time_constraint_id_constraint'), table_name='time_constraint')
    op.drop_table('time_constraint')
    op.drop_index(op.f('ix_mood_questionnaire_id_user'), table_name='mood_questionnaire')
    op.drop_index(op.f('ix_mood_questionnaire_id_questionnaire'), table_name='mood_questionnaire')
    op.drop_table('mood_questionnaire')
    op.drop_index(op.f('ix_goal_id_user'), table_name='goal')
    op.drop_index(op.f('ix_goal_id_goal'), table_name='goal')
    op.drop_table('goal')
    op.drop_index(op.f('ix_user_id_user'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
